### ISSUE TITLE
Custom User model with no username field

### ISSUE THREAD

**Issue by rjsnh1522** [Raekkeri/django-requestlogs#12]
Custom User model with no username field

it raises exception if i dont have username in my user model. I have custom user model with no username field

**Comment by Raekkeri** [comment]
> Custom User model with no username field
> 
> it raises exception if i dont have username in my user model. I have custom user model with no username field

For the time being, you can use a workaround by specifying your own serializer class to be used to serialize the log message. The default serailizer is specified at https://github.com/Raekkeri/django-requestlogs/blob/master/requestlogs/storages.py#L25 , and you can use it as a base serializer and override the `user` field, e.g.:

```
class CustomUserSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    field_in_my_user_model = serializers.CharField()


class MyEntrySerializer(requestlogs.storages.BaseEntrySerializer):
    user = CustomUserSerializer() 
```

And finally configure requestlogs to use this serializer:

```
REQUESTLOGS = {
    ...
    'SERIALIZER_CLASS': 'path.to.MyEntrySerializer',
    ...
}
```

**Comment by m4riok** [comment]
You would most likely have to subclass RequestLogEntry and overload the user property so that ret matches the data you intend on logging for the user.
