### ISSUE TITLE
django-ipware dependence in README.md

### ISSUE THREAD

**Issue by siwei-li** [Raekkeri/django-requestlogs#13]
Thank you for your work! 

I have noticed, though, that django-ipware package is required for retrieving IP addresses in the logs.  It might be helpful to mention that in the document.

---
There's also a typo here: 

> The feature is enabled by adding requestlogs.middleware.RequestLogsMiddleware to the MIDDLEWARE setting:

Should actually be

> The feature is enabled by adding requestlogs.middleware.RequestIdMiddleware to the MIDDLEWARE setting:

**Comment by Raekkeri** [comment]
Thanks for your input, I've adjusted the documentation a bit.

> 
> There's also a typo here:
> 
> > The feature is enabled by adding requestlogs.middleware.RequestLogsMiddleware to the MIDDLEWARE setting:
> 
> Should actually be
> 
> > The feature is enabled by adding requestlogs.middleware.RequestIdMiddleware to the MIDDLEWARE setting:

^ Good catch!
