### ISSUE TITLE
Save Log to database

### ISSUE THREAD

**Issue by rdomga** [Raekkeri/django-requestlogs#20]
Please,

I'm new in Django and DRF
I want to know ho to logg all my message in a database table
Thank you in advance for your response
DOMGA

**Comment by Raekkeri** [comment]
First, a word of warning: storing all request logs into the database can get your database clogged up, especially if the server receives a high amount of requests.

Storing the entries of requestlogs in the database, however, should be quite straightforward. For example, you could create a model such as:

```
class LogEntry(models.Model):
    log_data = models.TextField()
    # ... and other fields, for example, to store some log data in more primitive format, such as "user_id"
```

Then create a custom storage handler and overwrite the `store` function:

```
from requestlogs.storages import LoggingStorage
from yourpackage.models import LogEntry

class DBStorage(LoggingStorage):
    def store(self, entry):
        LogEntry.objects.create(log_data=self.prepare(entry))
```

Finally configure requestlogs to use the `DBStorage`:

```
REQUESTLOGS = {
    ...
    'STORAGE_CLASS': 'yourpackage.path.to.DBStorage',
    ...
}
```
