### ISSUE TITLE
Update for Django 4.0

### ISSUE THREAD

**Issue by mosh7890** [Raekkeri/django-requestlogs#24]
Hey, really making great use of this package. Wanted to ask if this would get updated to support Django 4. 
Thanks!

**Comment by Raekkeri** [comment]
Thanks,
support for Django 4 should be coming soon. Unittests seem to already pass as they are, so if you ignore the deps you might be able to use this with Django 4 already.

**Comment by Raekkeri** [comment]
Supported in 0.3.0.
